### ISSUE TITLE
Comparision bug

### ISSUE THREAD

**Issue by Aisupurinesu** [vukaspajic/IFC-Werkzeug#3]
**Describe the bug**
Visualisation of both models during comparision doesnt work. 

**To Reproduce**
1. Adding two ifc files.
2. Version comparison.
3. Choosing options:
![image](https://github.com/vukaspajic/IFC-Werkzeug/assets/72505519/a977c831-e026-4190-913f-b791e9a367e0)
4. And screen looks like this:
![image](https://github.com/vukaspajic/IFC-Werkzeug/assets/72505519/6db69b1a-932b-41c5-87bc-dd34b74d6a7c)

**Desktop (please complete the following information):**
 - Edge

**Comment by vulevukusej** [comment]
potentially related to https://github.com/IfcOpenShell/IfcOpenShell/issues/4110

**Comment by vukaspajic** [comment]
Fixed in update to be pushed tonight. Thanks @Aisupurinesu
